### ISSUE TITLE
List of projects that are good candidates for study

### ISSUE THREAD

**Issue by vsoch** [urlstechie/urlchecker-analysis#1]
From issue urlstechie/urlchecker-python#13:

> But here is an idea - what about some kind of fun project where we involve the research community, but do our own small analysis, and then that serves as a writeup that we can share on social media and encourage folks to use it? What I'd want to do is assemble a list of documentation served on repositories that are research oriented / groups, and then programmatically run the checker for all of them to calculate the number of total links, number of broken, etc. Actually, if we add the ability to specify an output file, we could even put the entire results into a data repository, include the scripts for running, and heck, if we can make an argument for a research tool for documentation (that has shown purpose and we have some hypothesis / conclusions about links) we might even have enough to at least submit a paper to JoSS (and then to ArXiv if it's rejected). What do you think? So my thinking for moving forward - after results can be saved to file:

- We can make a list of repos that we want to run it for (that we would eventually want to suggest / PR to add the check) THIS ISSUE HERE.
 - Once we have that, then I'll start our little data analysis to check repos! Would we want to do something that not only runs across repos, but also across time? Would it be interesting to set up as a CI automated job that can collect metrics over a longer period of time?
 - we we can write it up, perhaps submit first or just share it
 - and then to all repos we test, we can offer to help fix the broken links by way of a PR to use the action.

This sounds like fun! I'm totally willing to take on the bulk of work stated above, I haven't done a little fun project like this in a while. Let me know your thoughts!

-------------
 - https://github.com/jamespjh/eResearch-meeting-list

**Comment by vsoch** [comment]
Done!

**Comment by SuperKogito** [comment]
So after searching a bit and checking some projects, I came up with the list below. The projects listed below were not chosen for any specific criteria. I just tried to diversify the repositories (Python, JS, Html) but it is still missing others (c., c++ etc.). I also tried to include projects that are currently maintained and include many links.

### Python projects
 
- https://github.com/juand-r/entity-recognition-datasets
- https://github.com/apacha/OMR-Datasets
- https://github.com/weecology/retriever
- https://github.com/google-research/meta-dataset
- https://github.com/tensorflow/datasets
- https://github.com/microsoft/nni
- https://github.com/aaron-xichen/pytorch-playground
- https://github.com/qiime2/docs
- https://github.com/MycroftAI/documentation
- https://github.com/sebastianruder/NLP-progress

### Js projects and websites. 
This a list of various active projects of interest with many links. 

- https://github.com/up-for-grabs/up-for-grabs.net
- https://github.com/docker/docker.github.io
- https://github.com/microsoft/TypeScript-wiki
- https://github.com/sendgrid/docs
- https://github.com/mozilla/infosec.mozilla.org

### Curated lists repositories are very interesting for us
This will help us test urlchecker with .md files

- https://github.com/trimstray/the-book-of-secret-knowledge
- https://github.com/tiimgreen/github-cheat-sheet
- https://github.com/fffaraz/awesome-cpp
- https://github.com/enaqx/awesome-react
- https://github.com/sindresorhus/awesome
- https://github.com/sindresorhus/awesome-nodejs
- https://github.com/prakhar1989/awesome-courses
- https://github.com/MaximAbramchuck/awesome-interview-questions
- https://github.com/matiassingers/awesome-readme
- https://github.com/tuvtran/project-based-learning


### Academic projects and courses

- https://github.com/microsoft/AcademicContent
- https://github.com/gcushen/hugo-academic
- https://github.com/kubernetes/website
- https://github.com/swagger-api/swagger-codegen
- https://github.com/webpack-contrib/awesome-webpack

### HTML documentations 

- https://github.com/RDFLib/pyLODE
- https://github.com/ctf-wiki/ctf-wiki
- https://github.com/nginxinc/nginx-wiki
- https://github.com/treehouses/treehouses.github.io
- https://github.com/NyaaCat/wiki

**Comment by SuperKogito** [comment]
Let me know what you think of it and which ones we should add ;)

**Comment by vsoch** [comment]
These are great! I don't see why we shouldn't add all of them? It's a very nice range of types of repos.

**Comment by vsoch** [comment]
I need to finish up working on an API, but after that I should be able to put some time into this! If not today, definitely this week.
